apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-2b361b1a-da76-4285-8f48-b7781ad58758
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-gitea-postgresql-0
    namespace: gitea
  hostPath:
    path: /var/local-path-provisioner/pvc-2b361b1a-da76-4285-8f48-b7781ad58758_gitea_data-gitea-postgresql-0
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
  name: data-gitea-postgresql-0
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-2b361b1a-da76-4285-8f48-b7781ad58758
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-bbbd47d8-b241-46a8-af5d-08270529a12d
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitea-shared-storage
    namespace: gitea
  hostPath:
    path: /var/local-path-provisioner/pvc-bbbd47d8-b241-46a8-af5d-08270529a12d_gitea_gitea-shared-storage
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gitea-shared-storage
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-bbbd47d8-b241-46a8-af5d-08270529a12d
