apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: the-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.25.0.50-172.25.0.70
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - the-pool